// Centralized stock imagery and mock dataset for SIM Racing Nigeria

const IMGS = {
  hero: 'https://images.unsplash.com/photo-1771440571270-e27b63085a48?w=1920&h=1080&fit=crop&auto=format',
  wheel: 'https://images.unsplash.com/photo-1771920800290-53f22e5ac3f8?w=900&h=600&fit=crop&auto=format',
  member: 'https://images.unsplash.com/photo-1620855522342-de6d0ad7c3d7?w=600&h=600&fit=crop&auto=format',
  race1: 'https://images.unsplash.com/photo-1699138346782-8a8b211c3da2?w=900&h=500&fit=crop&auto=format',
  race2: 'https://images.unsplash.com/photo-1699138346491-d6f4c7e04b85?w=900&h=500&fit=crop&auto=format',
  race3: 'https://images.unsplash.com/photo-1635414764966-682bd029bb01?w=900&h=500&fit=crop&auto=format',
};

const GAMES = [
  {
    id: 'iracing',
    name: 'iRacing',
    shortName: 'iRacing',
    genre: 'GT & Endurance',
    img: IMGS.race1,
    description: 'The backbone of SRN league racing — official series, a strict safety rating, and the deepest field of Nigerian drivers.',
  },
  {
    id: 'acc',
    name: 'Assetto Corsa Competizione',
    shortName: 'ACC',
    genre: 'GT & Endurance',
    img: IMGS.race2,
    description: 'GT3 and GT4 focused, home to the community Endurance Series and the West Africa Sim Racing Cup.',
  },
  {
    id: 'ac',
    name: 'Assetto Corsa',
    shortName: 'AC',
    genre: 'Touring & Classic',
    img: IMGS.race3,
    description: 'The modding platform of choice — community liveries, touring cars, and custom car packs live here.',
  },
  {
    id: 'rfactor2',
    name: 'rFactor 2',
    shortName: 'rF2',
    genre: 'Open Wheel',
    img: IMGS.wheel,
    description: 'A smaller but dedicated group races Formula Pro and prototype classes, known for deep setup tuning.',
  },
];

const ACTIVITIES = [
  {
    id: 'weekly-race-night-32',
    title: 'Weekly Race Night: GT3 Sprint Series',
    date: 'Jul 17, 2026',
    time: '8:00 PM WAT',
    location: 'Online — iRacing',
    type: 'Race Night',
    status: 'upcoming',
    description: 'Fixed-setup GT3 sprint races, open to all license levels. Practice server opens an hour before.',
    img: IMGS.race1,
  },
  {
    id: 'abuja-meetup',
    title: 'SRN Abuja Meetup',
    date: 'Jul 26, 2026',
    time: '2:00 PM WAT',
    location: 'Abuja — venue TBA',
    type: 'Meetup',
    status: 'upcoming',
    description: 'The first Abuja edition of the in-person meetup, following the turnout in Lagos. Bring your own wheel and pedals.',
    img: IMGS.race3,
  },
  {
    id: 'endurance-classic-final',
    title: 'SRN 6-Hour Endurance Classic — Final Round',
    date: 'Aug 2, 2026',
    time: '3:00 PM WAT',
    location: 'Online — ACC',
    type: 'Championship',
    status: 'upcoming',
    description: 'Two-driver teams, six hours, one track announced 48 hours before green flag.',
    img: IMGS.wheel,
  },
  {
    id: 'wasc-watch-party',
    title: 'West Africa Sim Racing Cup — Watch Party',
    date: 'Jul 10, 2026',
    time: '6:00 PM WAT',
    location: 'Online — Discord Stage',
    type: 'Watch Party',
    status: 'past',
    description: 'Community watch-along of the WASC final round, with live commentary from SRN members.',
    img: IMGS.race2,
  },
  {
    id: 'lagos-meetup-june',
    title: 'SRN Lagos Meetup',
    date: 'Jun 28, 2026',
    time: '1:00 PM WAT',
    location: 'Lagos — Lekki',
    type: 'Meetup',
    status: 'past',
    description: 'Sixty drivers, shared rigs, and a live bracket. The largest in-person SRN gathering to date.',
    img: IMGS.race3,
  },
  {
    id: 'season-4-launch',
    title: 'Season 4 2026 Launch Practice League',
    date: 'Jun 15, 2026',
    time: '7:00 PM WAT',
    location: 'Online — iRacing',
    type: 'Race Night',
    status: 'past',
    description: 'Two weeks of open practice sessions to help members adjust to the new season build.',
    img: IMGS.member,
  },
];

const NEWS = [
  {
    slug: 'wasc-clean-sweep',
    featured: true,
    tag: 'Championship',
    date: 'Jul 10, 2026',
    title: 'SRN Members Sweep Top 3 at West Africa Sim Racing Cup',
    excerpt: 'Chidi Okonkwo led a dominant Nigerian clean-sweep in the inaugural WASC, taking pole, fastest lap, and victory in the final round at Monza.',
    body: [
      'Nigeria arrived at the inaugural West Africa Sim Racing Cup as the team to beat, and left with every step of the podium. Chidi Okonkwo topped qualifying at Monza by three tenths, converted it into a lights-to-flag win, and set the fastest lap of the race for good measure.',
      'Behind him, fellow SRN drivers filled out second and third, giving the community its first clean-sweep at a regional event. The result caps a season in which SRN drivers have steadily climbed the West African rankings.',
      'Organizers have confirmed the Cup will return next season with a full six-round calendar, and SRN is already fielding a wider driver roster for the expanded format.',
    ],
    img: IMGS.race1,
    readTime: '4 min read',
    author: 'SRN Editorial',
  },
  {
    slug: 'budget-rig-guide',
    tag: 'Gear',
    date: 'Jul 8, 2026',
    title: 'How to Build a Competitive Sim Rig for Under ₦500k',
    excerpt: 'Our definitive guide to sourcing wheels, pedals, and rigs locally.',
    body: [
      'A common question in the SRN newcomer channel: what does it actually take to get race-ready without importing everything piece by piece? This guide breaks down a build that keeps total cost under ₦500,000 while staying competitive in club racing.',
      'The short version: prioritize the wheelbase and pedals over the monitor setup, buy a rig frame rather than building one from scratch unless you enjoy the project, and lean on the community marketplace for lightly used gear before ordering new.',
      'Full parts list, local supplier notes, and a step-by-step assembly walkthrough are maintained in the community resources hub.',
    ],
    img: IMGS.wheel,
    readTime: '8 min read',
    author: 'Bola Afolabi',
  },
  {
    slug: 'season-4-2026',
    tag: 'iRacing',
    date: 'Jul 5, 2026',
    title: 'Season 4 2026 Drops: What Nigerian Racers Need to Know',
    excerpt: 'New content, track updates, and how SRN drivers are preparing.',
    body: [
      "This season's build brings a handful of track updates and a new car to the fixed-setup ladder — welcome news for drivers who've been climbing the license ranks over the past year.",
      'SRN is running a dedicated practice league for the first two weeks of the season to help members get comfortable with the changes before jumping into official races.',
    ],
    img: IMGS.race2,
    readTime: '5 min read',
    author: 'Tunde Adeyemi',
  },
  {
    slug: 'lagos-meetup-recap',
    tag: 'Community',
    date: 'Jul 2, 2026',
    title: 'SRN Lagos Meetup Recap: 60 Drivers, One Track',
    excerpt: 'A look back at our biggest real-world gathering yet.',
    body: [
      'Sixty drivers, a dozen rigs, and one very loud viewing room — the SRN Lagos meetup was the largest in-person gathering the community has hosted. Members brought their own wheels and pedals to swap onto shared rigs, turning the afternoon into an informal gear-testing session as much as a race day.',
      'A live bracket ran on the main screen throughout, with the eventual winner taking home a set of donated pedals from a local sim racing retailer.',
      'Plans for a Abuja edition are already underway for later this year.',
    ],
    img: IMGS.race3,
    readTime: '3 min read',
    author: 'Adaeze Nwosu',
  },
  {
    slug: 'newcomer-mentor-program',
    tag: 'Community',
    date: 'Jun 18, 2026',
    title: 'Inside the SRN Newcomer Mentor Program',
    excerpt: 'How the community pairs first-time racers with mentors for their first ten races.',
    body: [
      'Starting competitive sim racing cold can be intimidating — unfamiliar rating systems, incident points, and race etiquette all at once. The newcomer mentor program pairs each new member with an experienced racer for their first ten official races.',
      'Since launching, the program has onboarded dozens of drivers, several of whom have gone on to podium in their first club series.',
    ],
    img: IMGS.member,
    readTime: '4 min read',
    author: 'Ifeoma Chukwu',
  },
  {
    slug: 'acc-endurance-round-3',
    tag: 'ACC',
    date: 'Jun 14, 2026',
    title: 'ACC Endurance Series Round 3: A Podium in the Rain',
    excerpt: 'Adaeze Nwosu came home third after a late-race downpour reshuffled the order.',
    body: [
      'A dry forecast turned into a soaked final stint at round 3 of the community ACC Endurance Series, catching several front-runners out on slick tyres. Adaeze Nwosu, who had pitted early for wets on a hunch, came through the chaos to finish third.',
      'The result moves her up to second in the endurance standings with two rounds remaining.',
    ],
    img: IMGS.race1,
    readTime: '3 min read',
    author: 'SRN Editorial',
  },
  {
    slug: 'formula-pro-setup-guide',
    tag: 'rFactor 2',
    date: 'Jun 25, 2026',
    title: 'A Setup Guide for the Formula Pro Class',
    excerpt: 'Bola Afolabi shares the baseline setup SRN drivers are using in rFactor 2.',
    body: [
      "rFactor 2's Formula Pro class rewards a stable rear end more than outright downforce, which trips up drivers coming over from other sims. This guide walks through the baseline setup the SRN rFactor 2 group has converged on this season.",
      'Expect a follow-up covering wet-weather adjustments once the current dry-only rotation ends.',
    ],
    img: IMGS.wheel,
    readTime: '6 min read',
    author: 'Bola Afolabi',
  },
  {
    slug: 'touring-car-livery-pack',
    tag: 'AC',
    date: 'Jun 30, 2026',
    title: 'New Community Livery Pack for the Touring Car Mod',
    excerpt: 'Emeka Eze releases a fresh set of liveries for the SRN touring car community mod.',
    body: [
      'Twelve new liveries, each inspired by a different Nigerian state, are now available for the community touring car mod. Emeka Eze, who leads the livery project, says a second pack focused on sponsor-style designs is already in progress.',
    ],
    img: IMGS.race2,
    readTime: '2 min read',
    author: 'Emeka Eze',
  },
];

const MEMBERS = [
  {
    id: 'chidi-okonkwo',
    name: 'Chidi Okonkwo',
    city: 'Abuja',
    rank: '#1 Nigeria',
    sim: 'iRacing',
    avatar: IMGS.member,
    joined: 'Mar 2023',
    bio: 'Reigning national #1. Chidi races GT3 and prototype classes and led the SRN clean-sweep at the West Africa Sim Racing Cup.',
    stats: { races: 214, wins: 38, podiums: 96 },
    activity: [
      { date: 'Jul 10, 2026', text: 'Won the West Africa Sim Racing Cup at Monza.' },
      { date: 'Jun 22, 2026', text: 'Set a new SRN track record at Spa in the GT3 class.' },
      { date: 'May 30, 2026', text: 'Hosted a setup workshop for new members.' },
    ],
  },
  {
    id: 'adaeze-nwosu',
    name: 'Adaeze Nwosu',
    city: 'Lagos',
    rank: '#4 Nigeria',
    sim: 'ACC',
    avatar: IMGS.member,
    joined: 'Aug 2023',
    bio: 'GT4 specialist and one of the driving forces behind SRN Lagos meetups. Known for consistency over a full race distance.',
    stats: { races: 168, wins: 21, podiums: 74 },
    activity: [
      { date: 'Jul 2, 2026', text: 'Organized the SRN Lagos meetup — 60 drivers, one track.' },
      { date: 'Jun 14, 2026', text: 'Podium finish at the ACC Endurance Series round 3.' },
    ],
  },
  {
    id: 'emeka-eze',
    name: 'Emeka Eze',
    city: 'Port Harcourt',
    rank: '#7 Nigeria',
    sim: 'AC',
    avatar: IMGS.member,
    joined: 'Jan 2024',
    bio: 'Vintage and touring car enthusiast who builds his own liveries for the community car pack.',
    stats: { races: 96, wins: 9, podiums: 33 },
    activity: [{ date: 'Jun 30, 2026', text: 'Released a new livery pack for the community touring car mod.' }],
  },
  {
    id: 'tunde-adeyemi',
    name: 'Tunde Adeyemi',
    city: 'Ibadan',
    rank: '#12 Nigeria',
    sim: 'iRacing',
    avatar: IMGS.member,
    joined: 'Oct 2024',
    bio: 'Newest driver to crack the national top 15. Builds and streams rig upgrades on weekends.',
    stats: { races: 61, wins: 4, podiums: 17 },
    activity: [{ date: 'Jul 8, 2026', text: 'Streamed a full Moza R21 rig build.' }],
  },
  {
    id: 'ifeoma-chukwu',
    name: 'Ifeoma Chukwu',
    city: 'Enugu',
    rank: '#15 Nigeria',
    sim: 'ACC',
    avatar: IMGS.member,
    joined: 'Feb 2024',
    bio: 'Runs the SRN newcomer program, pairing first-time racers with mentors for their first ten races.',
    stats: { races: 88, wins: 3, podiums: 22 },
    activity: [{ date: 'Jun 18, 2026', text: 'Onboarded 14 new racers into the mentor program.' }],
  },
  {
    id: 'bola-afolabi',
    name: 'Bola Afolabi',
    city: 'Lagos',
    rank: '#19 Nigeria',
    sim: 'rFactor 2',
    avatar: IMGS.member,
    joined: 'Nov 2023',
    bio: 'One of the few rFactor 2 regulars in the community — usually found tuning car setups late into the night.',
    stats: { races: 74, wins: 5, podiums: 19 },
    activity: [{ date: 'Jun 25, 2026', text: 'Shared a setup guide for the Formula Pro class.' }],
  },
  {
    id: 'grace-udoh',
    name: 'Grace Udoh',
    city: 'Abuja',
    rank: '#22 Nigeria',
    sim: 'iRacing',
    avatar: IMGS.member,
    joined: 'Apr 2024',
    bio: 'Endurance racing regular. Co-drove the SRN entry in the last two 6-hour community endurance events.',
    stats: { races: 52, wins: 2, podiums: 14 },
    activity: [{ date: 'May 12, 2026', text: 'Finished 2nd in the SRN 6-Hour Endurance Classic.' }],
  },
  {
    id: 'segun-bakare',
    name: 'Segun Bakare',
    city: 'Ibadan',
    rank: '#27 Nigeria',
    sim: 'ACC',
    avatar: IMGS.member,
    joined: 'Jul 2024',
    bio: 'Content creator covering SRN race weekends — highlight reels and onboard footage on the community media hub.',
    stats: { races: 43, wins: 1, podiums: 9 },
    activity: [{ date: 'Jul 3, 2026', text: 'Published the Lagos meetup highlight reel.' }],
  },
];

const MERCH = [
  {
    id: 'srn-tee-black',
    name: 'SRN Wordmark Tee — Black',
    price: 12000,
    category: 'Apparel',
    img: IMGS.race1,
    description: 'Heavyweight cotton tee with the SRN wordmark across the chest.',
  },
  {
    id: 'srn-hoodie',
    name: 'SRN Pit Crew Hoodie',
    price: 28000,
    category: 'Apparel',
    img: IMGS.race2,
    description: 'Fleece-lined hoodie with embroidered logo, built for late-night race nights.',
  },
  {
    id: 'srn-cap',
    name: 'SRN Racing Cap',
    price: 9000,
    category: 'Apparel',
    img: IMGS.race3,
    description: 'Structured six-panel cap with the SRN circle logo.',
  },
  {
    id: 'srn-sticker-pack',
    name: 'SRN Sticker Pack (5-piece)',
    price: 3500,
    category: 'Stickers',
    img: IMGS.wheel,
    description: 'Five die-cut stickers, perfect for a rig frame or laptop lid.',
  },
  {
    id: 'srn-decal-large',
    name: 'SRN Large Vinyl Decal',
    price: 5000,
    category: 'Stickers',
    img: IMGS.member,
    description: 'Large format vinyl decal for a car window, rig panel, or wall.',
  },
  {
    id: 'srn-mousepad',
    name: 'SRN Deskmat',
    price: 15000,
    category: 'Accessories',
    img: IMGS.race1,
    description: 'Extended deskmat sized for a full wheel-and-keyboard setup.',
  },
  {
    id: 'srn-lanyard',
    name: 'SRN Event Lanyard',
    price: 4000,
    category: 'Accessories',
    img: IMGS.race3,
    description: 'Woven lanyard from the West Africa Sim Racing Cup watch party.',
  },
];

const RIGS = [
  {
    id: 'lagos-beast',
    name: 'The Lagos Beast',
    ownerId: 'chidi-okonkwo',
    owner: 'Chidi Okonkwo',
    city: 'Abuja',
    img: IMGS.wheel,
    specs: [
      { label: 'CPU', value: 'Intel i9-13900K' },
      { label: 'GPU', value: 'RTX 4090 24GB' },
      { label: 'Wheel', value: 'Fanatec DD Pro' },
      { label: 'Pedals', value: 'Heusinkveld Sprint' },
      { label: 'Sim', value: 'iRacing + ACC' },
    ],
  },
  {
    id: 'phantom-v2',
    name: 'The Phantom V2',
    ownerId: 'tunde-adeyemi',
    owner: 'Tunde Adeyemi',
    city: 'Ibadan',
    img: IMGS.member,
    specs: [
      { label: 'CPU', value: 'Ryzen 9 7950X' },
      { label: 'GPU', value: 'RTX 4080 Super' },
      { label: 'Wheel', value: 'Moza R21' },
      { label: 'Pedals', value: 'Moza CRP Load Cell' },
      { label: 'Sim', value: 'iRacing' },
    ],
  },
  {
    id: 'endurance-special',
    name: 'Endurance Special',
    ownerId: 'grace-udoh',
    owner: 'Grace Udoh',
    city: 'Abuja',
    img: IMGS.race1,
    specs: [
      { label: 'CPU', value: 'Ryzen 7 7800X3D' },
      { label: 'GPU', value: 'RTX 4070 Ti' },
      { label: 'Wheel', value: 'Simagic Alpha Mini' },
      { label: 'Pedals', value: 'Simagic P2000' },
      { label: 'Sim', value: 'iRacing' },
    ],
  },
  {
    id: 'night-shift',
    name: 'Night Shift',
    ownerId: 'bola-afolabi',
    owner: 'Bola Afolabi',
    city: 'Lagos',
    img: IMGS.race2,
    specs: [
      { label: 'CPU', value: 'Intel i7-13700K' },
      { label: 'GPU', value: 'RTX 4070' },
      { label: 'Wheel', value: 'Thrustmaster T300RS' },
      { label: 'Pedals', value: 'Thrustmaster T3PA' },
      { label: 'Sim', value: 'rFactor 2' },
    ],
  },
  {
    id: 'clean-sweep-rig',
    name: 'Clean Sweep Rig',
    ownerId: 'adaeze-nwosu',
    owner: 'Adaeze Nwosu',
    city: 'Lagos',
    img: IMGS.race3,
    specs: [
      { label: 'CPU', value: 'Ryzen 9 7900X' },
      { label: 'GPU', value: 'RTX 4080' },
      { label: 'Wheel', value: 'Fanatec CSL DD' },
      { label: 'Pedals', value: 'Fanatec CSL Elite V2' },
      { label: 'Sim', value: 'ACC' },
    ],
  },
  {
    id: 'first-build',
    name: 'First Build',
    ownerId: 'segun-bakare',
    owner: 'Segun Bakare',
    city: 'Ibadan',
    img: IMGS.wheel,
    specs: [
      { label: 'CPU', value: 'Ryzen 5 7600' },
      { label: 'GPU', value: 'RTX 4060 Ti' },
      { label: 'Wheel', value: 'Logitech G923' },
      { label: 'Pedals', value: 'Logitech G923 (stock)' },
      { label: 'Sim', value: 'ACC' },
    ],
  },
];

function getArticle(slug) {
  return NEWS.find(a => a.slug === slug);
}

function getMember(id) {
  return MEMBERS.find(m => m.id === id);
}

function getRig(id) {
  return RIGS.find(r => r.id === id);
}

function formatNaira(n) {
  return `₦${n.toLocaleString('en-NG')}`;
}
